### ISSUE TITLE
Please add a new how to run guide 

### ISSUE THREAD

**Issue by saeedanabtawi** [SarahAbuirmeileh/Serve-and-Shine#67]
I'm in search of an open-source internal tool that can assist in building a directory of tech volunteers along with their skills. This particular project caught my interest. please add how to run guide.

**Comment by SarahAbuirmeileh** [comment]
That sounds fantastic! I'm excited to contribute a guide to help others
utilize the project efficiently. I'll make sure to include step-by-step
instructions on how to set up and run the tool, along with any additional
information that might be helpful for users.

**Comment by SarahAbuirmeileh** [comment]
Acomplete guid step-by-step has been added !
